apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photoprism2.fullname" . }}
  labels:
    {{- include "photoprism2.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  {{- end }}
  {{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | default (randAlphaNum 32) | b64enc }}
  {{- end }}
