version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism:latest
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "db:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
      PHOTOPRISM_SITE_URL: "${PHOTOPRISM_SITE_URL}"
      PHOTOPRISM_SITE_TITLE: "${PHOTOPRISM_SITE_TITLE}"
      PHOTOPRISM_SPONSOR: "true"
      PHOTOPRISM_EXPERIMENTAL: "true"
      PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_BACKUPS: "false"
      PHOTOPRISM_DISABLE_DOCKER: "false"
      PHOTOPRISM_DEFAULT_LOCALE: "en"
      HOME: "/photoprism"
    ports:
      - "2342:2342"
    volumes:
      - "../storage:/photoprism/storage"
      - "../originals:/photoprism/originals"
      - "../import:/photoprism/import"

  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    environment:
      MYSQL_DATABASE: "photoprism"
      MYSQL_USER: "photoprism"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "../database:/var/lib/mysql"

  brains:
    image: photoprism/brains:latest
    restart: unless-stopped
    depends_on:
      - photoprism
    volumes:
      - "../storage:/photoprism/storage"
    environment:
      BRAINS_AUTOSTART: "true"
      BRAINS_SERVER_ADDR: "photoprism:2342"
      BRAINS_SERVER_MODE: "public"
      BRAINS_SERVER_KEY: "${BRAINS_SERVER_KEY}"
      BRAINS_FACE_SIMILARITY: 0.65
      BRAINS_FACE_CLUSTER_SIZE: 40
      BRAINS_FACE_CLUSTER_CORE: 3
      HOME: "/photoprism"

volumes:
  storage:
  database:

networks:
  default:
    name: photoprism_network
